### PR TITLE
Added clear and score to the legend, fixes #5 & #6

### LINKED ISSUE #5: `c` to Clear?
`-` is great but sometimes I'm OCD and want to clear everything between tasks or tests.

### PR DESCRIPTION
**Pull request by kevinvangelder**
Also adds `c` to the keys bound to the `content.clear` command.

### CODE REVIEW

**Comment by skellock** [comment]
The problem is that these key commands are global.  

I agree they should be displayed on the screen, I just don't think they belong in every "command" menu.

**Comment by skellock** [comment]
Oh, there's also '.'.  Which is "repeat" last command.  It works for commands that are flagged as "repeatable".  Such as dispatching or querying redux.

**Comment by kevinvangelder** [comment]
Thanks for the feedback. Updated.

**Comment by skellock** [comment]
I'm ok with this for now.  at least they show in the main menu eh?

**Pull request merged**
